project:
  type: website
  output-dir: .

website:
  title: "pyPLNmodels"
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Tutorials for count data"
        contents:
          - index.qmd
          - model_specifying.qmd
          - basic_analysis.qmd
          - zero_inflation.qmd
          - autoreg.qmd
          - clustering.qmd
          - network_analysis.qmd
          - formulas.qmd

format:
  html:
    toc: true  # Enables per-page table of contents
    toc-depth: 3
    number-sections: true
    math: true
    css: custom_css_yml.css
    theme: cosme
    code-copy: true
